# Generated by Django 3.1.4 on 2021-11-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fikr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kim_tomonidan', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
    ]
