# Generated by Django 3.1.4 on 2021-11-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_fikr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fikr',
            name='slug',
        ),
    ]
