# Generated by Django 3.1.4 on 2021-11-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_remove_fikr_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
